name: nejla-common
version: '0.1.0.0'
synopsis: Common functionality for Nejla Reference Architecture applications
description: Common functionality for Nejla Reference Architecture applications.
category: Development
maintainer: info@nejla.com
copyright:
  - Nejla AB
  - '2014-2021'
license: BSD3
homepage: https://github.com/nejla/nejla-common

flags:
  new-singletons:
    default: true
    manual: false

when:
  - condition: impl(ghc >= 8.10)
    default-extensions:
      - StandaloneKindSignatures
  - condition: flag(new-singletons)
    then:
      dependencies:
        - singletons >=3.0
        - singletons-th
        - singletons-base
    else:
      dependencies:
        - singletons >=1.1 && < 3.0

dependencies:
  - aeson
  - bytestring
  - configurator
  - containers
  - data-default
  - esqueleto < 3.6
  - fast-logger
  - HUnit
  - insert-ordered-containers
  - lens
  - monad-control
  - monad-logger
  - persistent
  - persistent-postgresql
  - persistent-template
  - postgresql-simple
  - servant
  - servant-multipart
  - servant-server
  - servant-openapi3
  - string-interpolate
  - vinyl
  - openapi3
  - text
  - unordered-containers

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror=incomplete-patterns
    - -Werror=incomplete-uni-patterns
    - -Werror=incomplete-record-updates
    - -Werror=unused-local-binds
    - -Werror=unused-pattern-binds
    - -Werror=unused-top-binds
    - -Werror=unused-matches
    - -Werror=missing-signatures
    - -Werror=unused-foralls
    - -Wno-deprecations
    - -Wno-name-shadowing
    - -Wno-missed-extra-shared-lib
  # Only error in latest lts, avoids adding otherwise pointless conditionals
  when:
    - condition: impl(ghc >= 9.6)
      ghc-options:
        - -Werror=unused-imports
  exposed-modules:
    - NejlaCommon
    - NejlaCommon.Config
    - NejlaCommon.Helpers
    - NejlaCommon.JSON
    - NejlaCommon.Orphans
    - NejlaCommon.Sendmail
    - NejlaCommon.Test
    - NejlaCommon.Test.Postgres
    - NejlaCommon.Test.Json
    - NejlaCommon.Test.Logging
    - NejlaCommon.Test.Expectation
    - NejlaCommon.Persistence
    - NejlaCommon.Persistence.Util
    - NejlaCommon.Persistence.Compat
    - NejlaCommon.Persistence.Migration
    - NejlaCommon.Persistence.Migration.CLI
    - NejlaCommon.Persistence.SqlStatistics
    - NejlaCommon.OpenApi
    - NejlaCommon.OpenApi.Operation
    - NejlaCommon.OpenApi.Nullable
  dependencies:
    - base >=4.7 && <5.0
    - async
    - optparse-applicative
    - binary
    - case-insensitive >=1.2
    - exceptions >=0.8
    - foldl
    - gitrev
    - hspec
    - hspec-wai
    - hspec-wai-json
    - http-api-data >=0.3.1
    - http-types >=0.9
    - microstache
    - mime-mail
    - mtl >=2.2
    - path-pieces
    - process
    - random
    - random-shuffle
    - resourcet
    - stm
    - stm-chans
    - template-haskell >=2.12
    - th-lift-instances
    - time >=1.5
    - transformers
    - transformers-base
    - unliftio-core
    - uuid
    - wai
    - wai-extra
    - warp

tests:
  tests:
    main: Test.hs
    source-dirs: tests
    ghc-options: -threaded -Wall
    dependencies:
      - QuickCheck
      - async
      - base
      - exceptions
      - formatting
      - hspec
      - hspec-expectations
      - mtl
      - nejla-common
      - shelly
      - singletons
      - temporary
      - time
      - template-haskell
      - unliftio
    default-extensions:
      - OverloadedStrings
