name: nejla-common
version: '0.1.0.0'
synopsis: Common functionality for Nejla Reference Architecture applications
description: Common functionality for Nejla Reference Architecture applications.
category: Development
maintainer: info@nejla.com
copyright:
  - Nejla AB
  - '2014-2021'
license: BSD3
homepage: https://github.com/nejla/nejla-common

when:
  - condition: impl(ghc >= 8.10)
    default-extensions:
      - StandaloneKindSignatures

dependencies:
  - aeson
  - bytestring
  - configurator
  - containers
  - data-default
  - esqueleto
  - fast-logger
  - HUnit
  - interpolate
  - lens
  - monad-control
  - monad-logger
  - persistent
  - persistent-postgresql
  - persistent-template
  - postgresql-simple
  - text
  - unordered-containers

library:
  source-dirs: source
  ghc-options: -Wall
  exposed-modules:
    - NejlaCommon
    - NejlaCommon.Config
    - NejlaCommon.Helpers
    - NejlaCommon.Sendmail
    - NejlaCommon.Test
    - NejlaCommon.Test.Postgres
    - NejlaCommon.Test.Json
    - NejlaCommon.Test.Logging
    - NejlaCommon.Test.Expectation
    - NejlaCommon.Persistence.Migration
    - NejlaCommon.Persistence.SqlStatistics
  dependencies:
    - base >=4.7 && <5.0
    - async
    - binary
    - case-insensitive >=1.2
    - exceptions >=0.8
    - foldl
    - gitrev
    - hspec
    - hspec-wai
    - hspec-wai-json
    - http-api-data >=0.3.1
    - http-types >=0.9
    - microstache
    - mime-mail
    - mtl >=2.2
    - path-pieces
    - process
    - random
    - random-shuffle
    - resourcet
    - singletons >=1.1
    - stm
    - stm-chans
    - template-haskell >=2.12
    - th-lift-instances
    - time >=1.5
    - transformers
    - transformers-base
    - unliftio-core
    - uuid
    - wai
    - wai-extra
    - warp

tests:
  tests:
    main: Test.hs
    source-dirs: tests
    ghc-options: -threaded
    dependencies:
      - QuickCheck
      - async
      - base
      - formatting
      - hspec-expectations
      - mtl
      - nejla-common
      - shelly
      - singletons
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - tasty-th
      - temporary
      - time
      - template-haskell
      - unliftio
